function Test-ApplicationInstalled {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [hashtable]$Application,

        [string]$LogPath
    )

    switch ($Application.Source) {
        'winget' {
            $dscModule = Get-WingetDscModule -LogPath $LogPath
            if ($dscModule) {
                try {
                    $result = Invoke-WingetDscPackageResource -Method Test -Application $Application -LogPath $LogPath
                    if ($result -and $result.ContainsKey('Error') -and $result.Error) {
                        throw $result.Error
                    }

                    if ($result -and $result.ContainsKey('InDesiredState')) {
                        return [bool]$result.InDesiredState
                    }
                }
                catch {
                    if ($LogPath) {
                        Write-BootstrapLog -Path $LogPath -Level 'WARN' -Message ("winget DSC test failed for '{0}', falling back to winget CLI. {1}" -f $Application.Name, $_.Exception.Message)
                    }
                }
            }

            if (-not (Get-Command winget -ErrorAction SilentlyContinue)) {
                return $false
            }

            $output = & winget list --exact --id $Application.Id 2>$null | Out-String
            return $output -match [regex]::Escape($Application.Id)
        }
        'choco' {
            if (-not (Get-Command choco -ErrorAction SilentlyContinue)) {
                return $false
            }

            $output = & choco list --local-only --exact $Application.Id 2>$null | Out-String
            return $output -match "^$([regex]::Escape($Application.Id))"
        }
        default {
            return $false
        }
    }
}

function Get-DesiredPowerShellProfileContent {
    [Diagnostics.CodeAnalysis.SuppressMessageAttribute('PSAvoidAssignmentToAutomaticVariable', '', Justification = 'False positive: PowerShell profile content generation does not assign to $PROFILE.')]
    [Diagnostics.CodeAnalysis.SuppressMessageAttribute('PSUseApprovedVerbs', '', Justification = 'False positive: stale diagnostic references removed helper Ensure-WingetDscModule.')]
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [string]$RepositoryRoot,

        [Parameter(Mandatory)]
        [hashtable]$Configuration,

        [string]$OhMyPoshProfile
    )

    $lines = New-Object System.Collections.Generic.List[string]
    $baseProfilePath = Join-Path $RepositoryRoot 'Config\Applications\PowerShell\profile.ps1'

    $lines.Add('# Generated by ClientBootstrap. Manual changes may be overwritten.')
    $lines.Add('')

    if (Test-Path -Path $baseProfilePath) {
        foreach ($line in (Get-Content -Path $baseProfilePath)) {
            $lines.Add($line)
        }
        $lines.Add('')
    }

    foreach ($fragment in @($Configuration.PowerShellProfileFragments | Select-Object -Unique)) {
        $fragmentPath = Resolve-ConfigPath -RepositoryRoot $RepositoryRoot -RelativePath $fragment
        if (-not (Test-Path -Path $fragmentPath)) {
            continue
        }

        $lines.Add("# Fragment: $fragment")
        foreach ($line in (Get-Content -Path $fragmentPath)) {
            $lines.Add($line)
        }
        $lines.Add('')
    }

    if ($OhMyPoshProfile) {
        $ohMyPoshConfigPath = Join-Path $RepositoryRoot ("Config\Applications\OhMyPosh\Profiles\$OhMyPoshProfile.omp.json")
        $escapedProfilePath = $ohMyPoshConfigPath.Replace("'", "''")
        $lines.Add('if (Get-Command oh-my-posh -ErrorAction SilentlyContinue) {')
        $lines.Add("    oh-my-posh init pwsh --config '$escapedProfilePath' | Invoke-Expression")
        $lines.Add('}')
    }

    return ($lines -join [Environment]::NewLine).TrimEnd() + [Environment]::NewLine
}

function Test-TextContentMatches {
    [CmdletBinding()]
    param(
        [AllowNull()]
        [string]$Expected,

        [AllowNull()]
        [string]$Actual
    )

    $normalize = {
        param([AllowNull()][string]$Value)

        if ($null -eq $Value) {
            return ''
        }

        return (($Value -replace "`r`n", "`n" -replace "`r", "`n").TrimEnd())
    }

    return (& $normalize $Expected) -eq (& $normalize $Actual)
}

function Get-DefaultPowerShellProfileTarget {
    return Join-Path $HOME 'Documents\PowerShell\Microsoft.PowerShell_profile.ps1'
}

function Invoke-WingetPackageOperation {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [hashtable]$Application,

        [Parameter(Mandatory)]
        [string]$LogPath
    )

    if (-not $Application.Id) {
        throw ("Application '{0}' is missing Id for winget DSC." -f $Application.Name)
    }

    Write-BootstrapLog -Path $LogPath -Message ("Using winget DSC for '{0}'" -f $Application.Name)
    $result = Invoke-WingetDscPackageResource -Method Set -Application $Application -LogPath $LogPath -InstallModuleIfMissing

    if ($result.Error) {
        throw $result.Error
    }
}

function Invoke-WrapperPackageOperation {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [hashtable]$Application,

        [Parameter(Mandatory)]
        [string]$LogPath
    )

    Write-BootstrapLog -Path $LogPath -Level 'WARN' -Message ("Source '{0}' for application '{1}' is currently scaffolded only. No installation was executed." -f $Application.Source, $Application.Name)
}

function Invoke-ReportMode {
    [Diagnostics.CodeAnalysis.SuppressMessageAttribute('PSAvoidAssignmentToAutomaticVariable', '', Justification = 'False positive on profile-related parameter names in reporting.')]
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [string]$RepositoryRoot,

        [Parameter(Mandatory)]
        [hashtable]$Configuration,

        [Parameter(Mandatory)]
        [System.Collections.IEnumerable]$Applications,

        [Parameter(Mandatory)]
        [System.Collections.IEnumerable]$PowerShellRepositories,

        [Parameter(Mandatory)]
        [System.Collections.IEnumerable]$PowerShellModules,

        [string]$OhMyPoshProfile,

        [Parameter(Mandatory)]
        [string]$LogPath
    )

    foreach ($application in $Applications) {
        $installed = Test-ApplicationInstalled -Application $application -LogPath $LogPath
        $status = if ($installed) { 'OK' } else { 'MISSING' }
        $message = '{0} application {1} via {2}' -f $status, $application.Name, $application.Source
        Write-BootstrapLog -Path $LogPath -Level ($(if ($installed) { 'OK' } else { 'WARN' })) -Message $message
    }

    Invoke-ReportPowerShellRepositories -Repositories $PowerShellRepositories -LogPath $LogPath
    Invoke-ReportPowerShellModules -Modules $PowerShellModules -LogPath $LogPath

    foreach ($folder in @($Configuration.Folders | Select-Object -Unique)) {
        $expandedFolder = $ExecutionContext.InvokeCommand.ExpandString($folder)
        $exists = Test-Path -Path $expandedFolder
        $status = if ($exists) { 'OK' } else { 'MISSING' }
        Write-BootstrapLog -Path $LogPath -Level ($(if ($exists) { 'OK' } else { 'WARN' })) -Message ("{0} folder {1}" -f $status, $expandedFolder)
    }

    $targetProfile = Get-DefaultPowerShellProfileTarget
    $desiredContent = Get-DesiredPowerShellProfileContent -RepositoryRoot $RepositoryRoot -Configuration $Configuration -OhMyPoshProfile $OhMyPoshProfile
    $profileExists = Test-Path -Path $targetProfile
    $currentContent = if ($profileExists) { Get-Content -Path $targetProfile -Raw } else { $null }
    $profileMatches = $profileExists -and (Test-TextContentMatches -Expected $desiredContent -Actual $currentContent)

    if ($profileMatches) {
        Write-BootstrapLog -Path $LogPath -Level 'OK' -Message ("OK PowerShell profile {0}" -f $targetProfile)
    }
    else {
        Write-BootstrapLog -Path $LogPath -Level 'WARN' -Message ("MISSING or changed PowerShell profile {0}" -f $targetProfile)
    }

    if ($OhMyPoshProfile) {
        Write-BootstrapLog -Path $LogPath -Message ("Effective Oh My Posh profile: {0}" -f $OhMyPoshProfile)
    }
}

function Invoke-EnforceMode {
    [Diagnostics.CodeAnalysis.SuppressMessageAttribute('PSAvoidAssignmentToAutomaticVariable', '', Justification = 'False positive on profile-related parameter names in enforcement.')]
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [string]$RepositoryRoot,

        [Parameter(Mandatory)]
        [hashtable]$Configuration,

        [Parameter(Mandatory)]
        [System.Collections.IEnumerable]$Applications,

        [Parameter(Mandatory)]
        [System.Collections.IEnumerable]$PowerShellRepositories,

        [Parameter(Mandatory)]
        [System.Collections.IEnumerable]$PowerShellModules,

        [string]$OhMyPoshProfile,

        [Parameter(Mandatory)]
        [string]$LogPath
    )

    foreach ($folder in @($Configuration.Folders | Select-Object -Unique)) {
        $expandedFolder = $ExecutionContext.InvokeCommand.ExpandString($folder)
        if (-not (Test-Path -Path $expandedFolder)) {
            $null = New-Item -Path $expandedFolder -ItemType Directory -Force
            Write-BootstrapLog -Path $LogPath -Message ("Created folder {0}" -f $expandedFolder)
        }
        else {
            Write-BootstrapLog -Path $LogPath -Level 'OK' -Message ("Folder already present {0}" -f $expandedFolder)
        }
    }

    Invoke-EnforcePowerShellRepositories -Repositories $PowerShellRepositories -LogPath $LogPath
    Invoke-EnforcePowerShellModules -Modules $PowerShellModules -LogPath $LogPath

    foreach ($application in $Applications) {
        if (Test-ApplicationInstalled -Application $application -LogPath $LogPath) {
            Write-BootstrapLog -Path $LogPath -Level 'OK' -Message ("Application already installed: {0} via {1}" -f $application.Name, $application.Source)
            continue
        }

        switch ($application.Source) {
            'winget' {
                Write-BootstrapLog -Path $LogPath -Message ("Installing {0} via winget DSC" -f $application.Name)
                Invoke-WingetPackageOperation -Application $application -LogPath $LogPath
            }
            default {
                Invoke-WrapperPackageOperation -Application $application -LogPath $LogPath
            }
        }
    }

    $targetProfile = Get-DefaultPowerShellProfileTarget
    $profileDirectory = Split-Path -Path $targetProfile -Parent
    if (-not (Test-Path -Path $profileDirectory)) {
        $null = New-Item -Path $profileDirectory -ItemType Directory -Force
    }

    $desiredContent = Get-DesiredPowerShellProfileContent -RepositoryRoot $RepositoryRoot -Configuration $Configuration -OhMyPoshProfile $OhMyPoshProfile
    Set-Content -Path $targetProfile -Value $desiredContent -Force
    Write-BootstrapLog -Path $LogPath -Message ("Updated PowerShell profile {0}" -f $targetProfile)

    if ($OhMyPoshProfile) {
        Write-BootstrapLog -Path $LogPath -Message ("Configured Oh My Posh profile {0}" -f $OhMyPoshProfile)
    }
}
